name: Cloudflare Pages

concurrency:
  group: "cloudflare-pages"
  cancel-in-progress: false

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
    paths:
      - "packages/frontend/**"

jobs:
  publish:
    name: Publish to Cloudflare Pages
    runs-on: ubuntu-latest
    environment: better-vinwiki (Production)
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Build
        env:
          REACT_APP_NAME: ${{ vars.REACT_APP_NAME }}
          REACT_APP_URL: ${{ vars.REACT_APP_URL }}
          REACT_APP_DESCRIPTION: ${{ vars.REACT_APP_DESCRIPTION }}
          REACT_APP_SLOGAN: ${{ vars.REACT_APP_SLOGAN }}
          REACT_APP_API_URL: ${{ vars.REACT_APP_API_URL }}
          REACT_APP_MEDIA_API_URL: ${{ vars.REACT_APP_MEDIA_API_URL }}
          REACT_APP_MEDIA_CDN_URL: ${{ vars.REACT_APP_MEDIA_CDN_URL }}
          REACT_APP_API_CLIENT: ${{ vars.REACT_APP_API_CLIENT }}
        run: npx lerna run build --scope=@better-vinwiki/frontend

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: better-vinwiki
          directory: ./packages/frontend/build
          branch: main
