name: Dependency Review

on:
  workflow_dispatch:
  pull_request:
    branches: "*"

permissions:
  contents: read

jobs:
  dependency-review:
    if: ${{ github.repository_owner == 'amattu2' }}
    runs-on: ubuntu-latest
    steps:
      # Clone repository
      - name: "Checkout Repository"
        uses: actions/checkout@v3

      # Check dependencies
      - name: "Dependency Review"
        uses: actions/dependency-review-action@v2
